[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

  [build]
  command = "npm install && npm run build"
  functions = "netlify/functions"